### ISSUE TITLE
autoconf scripts outdated, assume libtool can handle the ar syntax on Windows, which is wrong

### ISSUE THREAD

**Issue by wrobelda** [libofx/libofx#48]
The current autoconf scripting assumes libtool handles the `ar` syntax, which causes errors on Windows.
Running `autoreconf` fixes it. 

I don't have the log file handy now, but can provide if needed.

**Comment by cstim** [comment]
But does this require any change in the source code (i.e. git repository)? Or is this rather a request to have the downloadable tarball be generated with a certain autotools version greater than xy? The latest tarballs were generated with autoconf=2.69; feel free to look up whether we should use a newer version instead.

**Comment by jralls** [comment]
The best solution would be to change the build to CMake or meson. Autotools is generally obsolete and little maintained; libtool in particular has degenerated into being [actively harmful](https://gitlab.gnome.org/GNOME/librsvg/-/issues/787) and is anyway superfluous. @wrobelda's problem is probably due to a mismatch between the libtool version in the tarball and the one he had installed.
