### ISSUE TITLE
Recent SourceForge releases are inconsistent.

### ISSUE THREAD

**Issue by jralls** [libofx/libofx#58]
![Screen Shot 2022-04-28 at 11 13 42 AM](https://user-images.githubusercontent.com/58910/165819665-1d7bc637-b2b2-4b72-9560-f4080cdfbb99.png)
![Screen Shot 2022-04-28 at 11 14 52 AM](https://user-images.githubusercontent.com/58910/165819844-0245d223-d3e3-4748-b2a5-a8dc5755f064.png)

Also in the libofx directory instead of having separate subdirectories for each release there are loose tarballs for libofx-0.9.12 through libofx-0.10.4.

**Comment by cstim** [comment]
I changed the sourceforge page to use their new "github integration" feature, because I'm tired of logging into the ugly sf.net page just for creating one stupid folder and uploading extra files, when github can do this much easier anyway, and the sourceforge UX sucks since long time anyway.

Hence in the future only the new scheme should apply anyway.

Needless to say that the feature didn't explain this up front to me as an admin, or to anyone else... Hence: Good that you noticed, but I guess it's going to stick to this way now.

**Comment by cstim** [comment]
Looking at this again, it is indeed a side-effect of wanting to skip the extra sourceforge management step. At Github, you will find the download at this URL `https://github.com/libofx/libofx/releases/download/0.10.5/libofx-0.10.5.tar.gz` and apparently the API integration mirrors this to sourceforge at a similar URL. Hence I guess the gnucash-on-windows script can and should change the URL now.

**Comment by jralls** [comment]
@cstim, Thanks for the explanation. We've switched all of the GnuCash-on-foo builds to pull from GitHub.
