### ISSUE TITLE
Still slightly confused about SP_MULTI_BYTE usage

### ISSUE THREAD

**Issue by wrobelda** [libofx/libofx#70]
See the code I came up with at: https://github.com/libofx/libofx/blob/28afdfaa785cc6f2aa7ef0f036fdd96cc6be765c/CMakeLists.txt#L109

It checks whether the OpenSP's `config.h` has `#define SP_MULTI_BYTE 1`. I based that on the `config.h` files from the distributions I came across. 

However, I noticed that the OpenSP itself doesn't check its value, but rather presence only, so I suppose there's a chance that a `config.h` might exist out there that does `#define SP_MULTI_BYTE` only, which the aforementioned code would actually ignore and assume it was, in fact, undefined.. 

Rather unlikely, but worth taking into consideration.

For what it's worth, I am working on upstreaming the FindOpenSP module (https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7470), hence this mind-wandering.

**Comment by benoitg** [comment]
A more pressing issue (this a from the FAQ, before the CMake refactoring), is the the value cannot be trusted.  The FAQ used to have this sentence "Unfortunately, the auto-detection of this option was too fragile to release, because distros do not always distribute the config.h OpenSP was truly compiled with.  If the devel package for opensp was not compiled at the same time as the lib, it may give wrong value."  Pretty sure I wrote that many years ago, I don't know if it's still an issue, but I'm having a hard time believing it has, considering OpenSP hasn't seen a release in nearly 2 decades.

**Comment by wrobelda** [comment]
Based on what I saw in all popular distributions, the OpenSP packages are being actively maintained, with some downstream fixes checked-in every now and then. I'd assume that the config.h would, therefore, reflect the `SP_MULTI_BYTE` correctly, but obviously that's just an assumption. I also just realized that I aded an option to forcefully DISABLE it, but there's no option to forcefully ENABLE it. 

I added the SP_MULTI_BYTE detection upstream to the `FindOpenSP.cmake` module, using `check_symbol_exists`, as opposed grepping though the `config.h`. Once it gets approved, I'll create a PR here with a backport of it and relevant changes, including the ability to forcefully ENABLE it.
